import Heading from '@/components/Heading';
import './globals.css'
import { Inter } from 'next/font/google'
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


function handleScroll(){
  console.log('toto');
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      
      <body className={inter.className}>
        {children}
        <PrismicPreview repositoryName={repositoryName} />
        </body>
    </html>
  )
}

