// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  important_text_and_image: dynamic(() => import("./ImportantTextAndImage")),
  prompt_slice: dynamic(() => import("./PromptSlice")),
  text: dynamic(() => import("./Text")),
  title_and_text: dynamic(() => import("./TitleAndText")),
};
